sudo: false
language: minimal  # Bazel downloads its own Go SDK
env:
  global:
    - BAZEL_VERSION=1.1.0
    - BAZEL_SHA256=1a552f4ce194860fbbd50eeb319f81788ddf50a849e92378eec72231cc64ef65
before_install:
  - |
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
    chmod +x install.sh
install:
  - |
    ./install.sh --user
    rm -f install.sh
script:
  - bazel build --config=ci //...
  - bazel-bin/linux_amd64_static_pure_stripped/bmc_exporter --version
