os: linux
language: shell  # N.B. Bazel downloads its own Go SDK
env:
  global:
  - BAZEL_VERSION=3.0.0
  - BAZEL_SHA256=eb7aaa85d81c6d1caa5352e0573817217d0c364302aeee923a5cdb04f26d2bd3
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- bazel build --config=ci //...
- bazel-bin/linux_amd64_static_pure_stripped/bmc_exporter --version
