os: linux
language: shell  # N.B. Bazel downloads its own Go SDK
env:
  global:
    - BAZEL_VERSION=2.1.1
    - BAZEL_SHA256=d6cea18d59e9c90c7ec417b2645834f968132de16d0022c7439b1e60438eb8c9
before_install:
  - |
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
    chmod +x install.sh
install:
  - |
    ./install.sh --user
    rm -f install.sh
script:
  - bazel build --config=ci //...
  - bazel-bin/linux_amd64_static_pure_stripped/bmc_exporter --version
