os: linux
dist: focal
language: go
go:
- 1.15.3  # Bazel still uses its own version
services:
- docker
env:
  global:
  - BAZEL_VERSION=3.7.0
  - BAZEL_SHA256=621089dc4d396612603a55f18f55acded29d9b21534ebaa99406a0b4b05029fb
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- |
  travis_wait bazel build --config=ci //...
  go build
  mkdir out
  bin/release out
  bazel run //:bmc_exporter -- --version
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  bazel run //:push-commit
  if [[ $TRAVIS_TAG ]]; then bazel run //:push-release; fi
deploy:
  provider: releases
  edge: true
  file_glob: true
  file: out/*
  token:
    secure: rYbVSILxxm+GzsIUJzot0jJkk4Fwu9yMQqawG5iaIT+k64SqVNPcEnNES0XJNibTtudzLTvWN4cQxiwYaCjONq+2Q3nm2L4QVe3OfzFMRZeHRykQ/FqETo1P4/iQNnYP8wdl4cko1anR094kCtmWmWaKCH5PH5MBcdgvqIUg7xqIfmQM2y/pRdpSZ7L+9I7G4xQBjy/WTA7TnHbxpUxljN9apOWTz3WARAP8VlzGmm9EEQ2rdLyI5Ob51VrmlubnqZbbj5LOlU5bRrARl0SappK7nrl+yqthzuyz9B3la40WzyGm7TeolqMD2WEUYh5/T8IRvKD239kY/u+6BgW1ZeQBmowbz+wj+EP08Xr6MBANyv4yS8pO7xE4UP5NfX0FakOf0kj/ZaHji5mFQVDb+eSOKfkUPP+hhGSHRMA53ikeCpoai0+Mxio1HORgOPZebukk8PJYMWI14HryU82jDPPa8TpS4FYvlSZi1OKLWhBeYIlwKSRQ44qaRhSvGY5R4P/KEx8aagsfl2CHm2zYEvWm6RwuFLOs7evJSgz7w2aEMhXdFT8ouxG7PiEpSW+8Q+ItGEmXpkYtSxlArqobqhozYKjCL2kbr4Hi/Bny4g6VdsUDfVZDwcTvhvAoS7PKvvujeHreXlq4LQx2cAk/J+ZnKatRhil1qfOA5Yl1+3c=
  on:
    repo: gebn/bmc_exporter
    tags: true
