sudo: false
language: minimal  # Bazel downloads its own Go SDK
env:
  global:
    - BAZEL_VERSION=0.29.1
    - BAZEL_SHA256=f87f0057cd7d6666e4d371267fbe27a9ed47f42e6663694a1cd755c8c6858baf
before_install:
  - |
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
    chmod +x install.sh
install:
  - |
    ./install.sh --user
    bazel shutdown  # prevents "WARNING: Running Bazel server needs to be killed, because the startup options are different."
    rm -f install.sh
script:
  - |
    bazel \
      --host_jvm_args=-Xmx7000m \
      --host_jvm_args=-Xms7000m \
      build \
      --config=ci \
      --noshow_progress \
      --noshow_loading_progress \
      --local_resources=7500,2,1.0 \
      //...
#  - |
#    bazel \
#      --host_jvm_args=-Xmx8000m \
#      --host_jvm_args=-Xms8000m \
#      test \
#      --config=ci \
#      --noshow_progress \
#      --noshow_loading_progress \
#      --local_resources=8500,2,1.0 \
#      //...
  - bazel-bin/linux_amd64_static_pure_stripped/bmc_exporter --version
